apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: zookeeper
  name: c2e-zookeeper-1
spec:
  containers:
  - env:
    - name: ZOO_MY_ID
      value: "2"
    - name: ZOO_SERVERS
      value: server.1=0.0.0.0:2888:3888;2181
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    image: confluentinc/cp-zookeeper:7.0.1
    name: c2e-zookeeper-1
    ports:
    - containerPort: 2181
    resources: {}
  restartPolicy: OnFailure
status: {}
