apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: kafka
  name: c2e-kafka-1
spec:
  containers:
  - env:
    - name: HOSTNAME_COMMAND
      value: hostname
    - name: KAFKA_ADVERTISED_LISTENERS
      value: INSIDE://c2e-kafka-1:9092,OUTSIDE://localhost:9094
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_CREATE_TOPICS
      value: control:1:1
    - name: KAFKA_DEFAULT_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: INSIDE
    - name: KAFKA_LISTENERS
      value: INSIDE://:9092,OUTSIDE://:9094
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    - name: KAFKA_LOG_RETENTION_BYTES
      value: "-1"
    - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
      value: "0"
    - name: KAFKA_DELETE_TOPIC_ENABLE
      value: "true"
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "true"
    - name: KAFKA_LOG_RETENTION_DAYS
      value: "2"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: c2e-zookeeper-1:2181
    - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
      value: "36000"
    - name: CONFLUENT_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR
      value: "1"
    image: confluentinc/cp-kafka:7.0.1
    name: c2e-kafka-1
    ports:
    - containerPort: 9092
    resources: {}
