config:
  outputs:
    - influxdb_v2:
        urls:
          - "http://c2e-influxdb2:80"
        token: ""
        bucket: "default"
        organization: "influxdata"
    - iotdb:
        host: c2e-iotdb
        user: root
        password: root
        convert_tags_to: fields
        name_prefix: root.cloud2edge.
        timestamp_precision: millisecond
    - opentsdb:
        host: c2e-opentsdb
        port: 4242
        prefix: tsd.cloud2edge.
  inputs:
    - statsd:
        service_address: ":8125"
        percentiles:
          - 50
          - 95
          - 99
        metric_separator: "_"
        allowed_pending_messages: 10000
        percentile_limit: 1000
    - kafka_consumer:
        brokers: ["c2e-kafka-1:9092"]
        topics: ["digitaltwins"]
        data_format: "json"
        tag_keys:
          - path
          - value
          - topic
        name_override: "digtwin"
