adminPassword: password

service:
  type: NodePort

persistence:
  enabled: true
  storageClassName: grafana

grafana.ini:
  plugins:
    allow_loading_unsigned_plugins: apache-iotdb-datasource,ertis-3-d-visualization-unity
