apiVersion: v1
kind: PersistentVolume
metadata:
  name: c2e-pv-grafana
spec:
  storageClassName: grafana
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opentwins/grafana
